### ISSUE TITLE
Tooltip not rendering on Firefox

### ISSUE THREAD

**Issue by ohall** [wwayne/react-tooltip#2]
I think this is because of how firefox deals with position.  Particularly `position:fixed;`

**Comment by wwayne** [comment]
@ohall Thanks, I have fixed that, that because I used event.x to get clientX, firefox only support event.clientX.
Current version is 0.1.8, I separate css from jsx because I want to add more style and give flexibility to the users in the future, so now you have to include css or sass file(in dist folder) into your project.
Thanks for finding issue :)

**Comment by ohall** [comment]
Works perfectly.  Thank you!
