### ISSUE TITLE
3.2.4 Update causing tests to fail.

### ISSUE THREAD

**Issue by mchadwickchennault** [wwayne/react-tooltip#252]
Since the update, all my tests are failing with the following error:

undefined is not a constructor (evaluating 'currentTarget.getAttribute('data-iscapture')')

**Comment by wwayne** [comment]
@mchadwickchennault I did some local test and google, no idea why you got this error. Latest update should have nothing to do with `isCapture`.

I don't know if it is because of I compiled it with node6, but I'm using babel, so it should be irrelevant I suppose. Anyway I use node4 to compile it again and publish new version 3.2.5, you can take a try

**Comment by wwayne** [comment]
Fixed in 3.2.7
