### ISSUE TITLE
No line break when tooltip text is dynamic

### ISSUE THREAD

**Issue by lovetann** [wwayne/react-tooltip#279]
I would like to have line breaks in my tooltip, but in stead the <br /> is displayed as text, and I can't figure out how to format it correctly. In short my code looks like this:

```
var tooltiptest = 'this is <br /> a test';

<div data-tip data-for='path'>Path</div>

<ReactTooltip id='path' type='light' multiline={true}>
            <span>{tooltiptest}</span>
 </ReactTooltip>
```

What am I doing wrong?

**Comment by huumanoid** [comment]
Hello, @lovetann. 

As far as I understand, if `<ReactTooltip>`'s children is present, it will be passed to `ReactTooltip.render` as is. You don't event need to set `multiline` to `true`.

So, I guess, the problem is that `React` itself sanitizes `tooltiptest`'s content. Try to use react elements/components instead of plain strings.
Please, let me know is it fine for you.

**Comment by huumanoid** [comment]
Of course, you've got a second option:
```jsx
var tooltiptest = 'this is <br /> a test';

<div data-tip={tooltiptest} data-for='path'>Path</div>

<ReactTooltip id='path' type='light' html={true} />
```

**Comment by lovetann** [comment]
Thanks for your reply! I ended up by putting the text inside a component.
