### ISSUE TITLE
Don't really need `findDOMNode`?

### ISSUE THREAD

**Issue by IanWang** [wwayne/react-tooltip#331]
Hi, I noticed that in the `Static Methods` section of the readme
there's a sample code like:
```js
<button onClick={() => { ReactTooltip.hide(findDOMNode(this.refs.foo)) }}></button>
```
But as what [react doc](https://facebook.github.io/react/docs/react-dom.html#finddomnode) mentions, if I get it right, use the `ref` can also access the DOM object.

> In most cases, you can attach a ref to the DOM node and avoid using findDOMNode at all.

the `findDOMNode` seems to be redundant?

**Comment by wwayne** [comment]
@IanWang Good point, I have to browse the source code to check my logic 😄  
To be short,  `findDOMNode(this.refs.foo)` will finally arrive at [here](https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L236)
```js
const targetArray = this.getTargetArray(this.props.id)
// e.currentTarget === findDOMNode(this.refs.foo)
const isMyElement = targetArray.some(ele => ele === e.currentTarget) 
``` 
`targetArray` is a list of browser native DOM nodes, so basically `findDOMNode(this.refs.foo)` should be a browser native DOM node. 
I remember `ref` is refs to a React virtual DOM node instead of a real DOM node. Not sure if React has updated `refs`,  if my understanding of `refs` is correct, `findDOMNode ` is needed here because it returns browser native DOM node.

**Comment by IanWang** [comment]
@wwayne thanks for your response.
I think the DOM from `ref` is the actual DOM ([React doc](https://facebook.github.io/react/docs/refs-and-the-dom.html))

> When the ref attribute is used on an HTML element, the ref callback receives the underlying DOM element as its argument. ... React will call the ref callback with the DOM element when the component mounts, and call it with null when it unmounts.

so when you match something got from `querySelector` and `ref`, it should be the same one.
Here's a [quick test](http://jsbin.com/sutajipolo/edit?js,console)

**Comment by wwayne** [comment]
Updated the README
Thanks for your explanation and findings 👍
