### ISSUE TITLE
Not working on Shadow DOM

### ISSUE THREAD

**Issue by osnysantos** [wwayne/react-tooltip#350]
I'm trying to use ReactTooltip in a project with ShadowDOM and it's not showing up, then I tried moving it out of ShadowDOM and it worked. So far I don't know the reason why isn't working. I can only think about CSS which is what ShadowDOM changes the default behavior.

This is the lib I'm using to create the ShadowDOM: https://github.com/Wildhoney/ReactShadow

Does someone faced the same issue and know if it's possible to get it working inside a ShadowDOM?

**Comment by snow-kbsd** [comment]
Hey, just to give you some idea. 

ReactTooltip uses document.querySelectorAll('') and document.querySelector to find tooltips with the tooltip attribute. This querySelect will not work within the shadow DOM since the shadow DOM is created separately from the browser DOM and querySelectorAll on the browser dom will not return any nodes within shadow DOMs.

You will need to change those querySelector calls to 
[yourelement].shadowRoot.querySelectorAll('...');

Generally, it seems to me that react tooltip is not compatible with the shadow dom at the moment.
