### ISSUE TITLE
Momentary double render of Tooltip

### ISSUE THREAD

**Issue by Ganasist** [wwayne/react-tooltip#356]
I see the Tooltip rendering momentarily in double, then reverting to proper single rendering automatically. This only happens sometimes, on certain components. In most other locations it works flawlessly.

Any suggestions? See attached

<img width="214" alt="screen shot 2017-12-01 at 16 57 19 2" src="https://user-images.githubusercontent.com/2892647/33490936-fe339e5c-d6b8-11e7-9c91-dd45adae850b.png">

**Comment by albertovilva** [comment]
If your use case is the same as mine what is happening is:

1. You added a <Component><ReactTooltip/></Component>
2. You are using that Component more than once.

Since the tooltip binds to the **data-for** attribute, its binding multiple tooltips to multiple triggers. Same thing happening to me. 

A solution to this would be pretty cool. Like injecting a random hash to the data-for attribute or somehting.

**Comment by Ganasist** [comment]
Yes the issue was non-unique data-for attributes in large lists. Once I added unique values there this issue cleared up. Also the tooltips seem snappier now. Thanks!

**Comment by albertovilva** [comment]
BTW A solution I came up with is creating the component as a stateful component. Set a uniqueID in the state object and update it with a random value onComponentWillMount(), use that value for your **data-for** attribute. That way every instance of your component gets a different ID. Hope it helps!
