### ISSUE TITLE
Render React components as content of tooltip?

### ISSUE THREAD

**Issue by anasanzari** [wwayne/react-tooltip#357]

**Comment by DanielDziubecki** [comment]
+1

**Comment by arun1001** [comment]
+1

**Comment by augbog** [comment]
Probably worth looking at this issue here: https://github.com/wwayne/react-tooltip/issues/329

There is a way to do it although it isn't really pretty. As far as I'm aware there are two main ways of doing it 

* you do the suggestion mentioned in the issue where you called `renderToStaticMarkup` and shove it into the data attribute
* you make the tooltip component you are hoping to render a child of the `<ReactTooltip>` -- this limits you to using that specific component so you can't use a dynamic component but it's cleaner.
