### ISSUE TITLE
Tooltip hides immediately

### ISSUE THREAD

**Issue by JFFby** [wwayne/react-tooltip#370]
Hey,
I am confused because my tooltip hides immediately and I don't understand why. You can watch it [here](https://www.screencast.com/t/2Llt30hV)
My code:

```
.map((node, index) => {
	const arrow = node.visualBlock as TreeArrow;
	const id = `arrow-menu-${node.visualBlock.blockId}`;
	return (
		<ReactTooltip
			id={id}
			getContent={this.getMenuItems(arrow)}
			effect='solid'
			place='bottom'
			key={index}
			className='menu-buttons'
			type='light'
			event='click'
			globalEventOff='click'
			isCapture={true}
		/>
	);
});
```
```
export const PlusButton = (props: PlusButtonProps) => {
	const yPosition = props.layoutObject.position.size.height / 2 - height / 2;
	const dateFor = `arrow-menu-${props.layoutObject.visualBlock.blockId}`;
	return (
		<svg
			className='plus-button-block'
			width={width}
			height={height}
			viewBox={`0 0 ${width} ${height}`}
			x={xPosition}
			y={yPosition}
			data-for={dateFor}
			data-tip={true}
			data-offset={tooltipOffset}
		>
		   ...
		</svg>
	);
};
```
Why I am getting in this hide function ?

**Comment by csantos1113** [comment]
I don't know how to fix this, but I know what the issue is. `globalEventOff='click'` is adding a click window listener which is being triggered right after you click your button (svg).

So when you click your button:
1. Opens the tooltip
2. Window listener
3. Hides the tooltip

**Comment by P0lip** [comment]
I observed the same buggy behaviour for a couple of tooltips.
In my particular case, it's caused by multiple listeners being attached to the same tip (please refer to screenshots).
For some reason, previously attached listeners aren't removed, while a new one gets attached.
With some doze of certainty, I may say that the reason is right here in [src/decorators/customEvent.js#52](https://github.com/wwayne/react-tooltip/blob/master/src/decorators/customEvent.js#L52). `customListener` seems to be overwritten by some other instance of tooltip, therefore it cannot be properly detached.
The workaround would be to map listener with actual item. We could incorporate usage of WeakMaps, so that we have weak references. It's should more reliable than the current approach and the bug should disappear.
@aronhelser WDYT?

I believe it's worth to mention, I import `react-tooltip` in our project just once, since we have a wrapper around it.

![image](https://user-images.githubusercontent.com/9273484/40273131-e0d9b1de-5bba-11e8-84ef-4794fe7c7dfb.png)
![image](https://user-images.githubusercontent.com/9273484/40273216-aaff44c8-5bbc-11e8-9599-d8c21f4efa2c.png)
