### ISSUE TITLE
4.2.11 no longer adds global __react_component_tooltip style

### ISSUE THREAD

**Issue by patricekaufmann** [wwayne/react-tooltip#650]
The project I use this on has 2 entry points and it works for one entry point while it does not work for the other one. It used to work for both. The global style tag is missing, containing 

```border-radius: 3px;
    display: inline-block;
    font-size: 13px;
    left: -999em;
    opacity: 0;
    padding: 8px 21px;
    position: fixed;
    pointer-events: none;
    transition: opacity 0.3s ease-out;
    top: -999em;
    visibility: hidden;
    z-index: 999;```

It happens only in 4.2.11, still working in 4.2.10.

**Comment by gajus** [comment]
If anyone runs into this while using next.js, just adding https://github.com/wwayne/react-tooltip/blob/master/src/index.scss to your global styles fixes the issue.

**Comment by sumthief** [comment]
Hey

I think my previous [PR](https://github.com/wwayne/react-tooltip/pull/636) could broke this functionality.

I tried to [fix it](https://github.com/sumthief/react-tooltip/commit/57fc1b3b8652cc0a6acc303f16af27d880106624) (looks like condition for `host` is unnecessary)

Checked on different apps:
* Clean CRA app
* Clean CRA app with tooltip rendered in Shadow DOM
* App inside iframe
* App inside Custom Element
* App inside Custom Element with Shadow DOM

Please could someone check [this fix](https://github.com/sumthief/react-tooltip/commit/57fc1b3b8652cc0a6acc303f16af27d880106624) and give feedback about it?

**Comment by gjvoosten** [comment]
@sumthief That doesn't appear to fix it for us: still shows a black line at the top of the content block (where the tooltip container is), shows the tooltip at the top of the content block instead of where it should be, and the tooltip also no longer hides itself. None of this is the case with 4.2.10.

**Comment by sumthief** [comment]
Okay, It was blind try to fix it and it doesn't work 🙁 

Can someone provide minimal repository for reproducing this issue?

**Comment by BoresXP** [comment]
This happened for me too.
Let's see why it happens. injectStyles should do the trick but it doesn't because [domRoots is empty](https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L191).
This happens because getTargetArray returns empty array :) [here](https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L180).
getTargetArray searches for any element [having data-tip attribute and data-for with id of current tooltip](https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L238) (or [no data-for](https://github.com/wwayne/react-tooltip/blob/master/src/index.js#L235) if tooltip has no id). Is there are no such element in DOM (you add them dynamically for example) default styles will never be inserted because injectStyles is called only once from componentDidMount.
Solution here will be simple: fallback do nearest head section to tooltip itself if no elements with data-tip exists.

**Comment by laurenz-glueck** [comment]
Will this issue be fixed anytime soon?

**Comment by gjvoosten** [comment]
I can confirm that release 4.2.14 does indeed fix this issue. :+1:
