### ISSUE TITLE
npm install error - Invalid tag name ">=^16.0.0"

### ISSUE THREAD

**Issue by benbro** [wwayne/react-tooltip#661]
I'm getting an error when running npm install:
```
Invalid tag name ">=^16.0.0": Tags may not have any characters that encodeURIComponent encodes.
```
I'm trying to install this [app](https://github.com/versatica/mediasoup-demo/blob/v3/app/package.json) using:
node.js v15.5.0
npm 7.3.0

https://github.com/npm/cli/issues/1734

**Comment by kbokhonko** [comment]
Hi. Have you found a solution for this?

**Comment by tokomeno-kaltura** [comment]
Having the same problem

before closing the issue please add the solution

**Comment by Jaygiri** [comment]
@tokomeno-kaltura try
```
npm install --legacy-peer-deps
```

**Comment by shapkarin** [comment]
@Jaygiri can you please explain why that happens? because I got that error at `npm update` and does not looks like I can fix it with `npm install --legacy-peer-deps`

**Comment by Jaygiri** [comment]
@shapkarin I haven't tested `--legacy-peer-deps` with `npm update`. May be that fix works for `npm install` since peer deps where ignored.  

It is possible that you have found some issue with npm because as per [documentation](https://docs.npmjs.com/cli/v7/commands/npm-update#strict-peer-deps) `--legacy-peer-deps` should work with `npm update`. 

That said I don't know what was the legacy behavior pre-v7. What you are getting is syntax error ">=^16.0.0" should be ">=16.0.0" and in current version for react-tooltip it is updated. 

I would recommend updating to latest version of react-tooltip manually and then running npm update.

**Comment by shapkarin** [comment]
@Jaygiri make sence, `npm i --save react-tooltip@latest` helped

**Comment by inerfil** [comment]
**`--legacy-peer-deps`** really works as band-aid, but it has to find a real solution.

**Comment by danielbarion** [comment]
Hi @inerfil, this is a closed issue related to V4, if are you having the same problem with V5, please let us know in a new issue, thanks!
