### ISSUE TITLE
Most recent version 4.2.14 breaks IE11

### ISSUE THREAD

**Issue by yc-yvonne** [wwayne/react-tooltip#677]
Likely from this: https://github.com/wwayne/react-tooltip/pull/668

Causes a `Internet Explorer throws SCRIPT5022: HierarchyRequestError` in IE11

Method of injection is not supported

**Comment by tiagomsg** [comment]
Have the same issue, it's definitely due to #668.

`parentNode.constructor.name` returns `undefined` on IE11, that causes this [switch](https://github.com/wwayne/react-tooltip/blob/55f11ad361a9d52166ea6b2a1bb614acc0d6ef35/src/index.js#L191) to assume the `domRoot` is the `parentNode` instead of `parentNode.head`.

Think the fix would be to just change that switch to:
```
    switch (parentNode.constructor.name) {
      case 'ShadowRoot':
        domRoot = parentNode;
        break;
      case 'HTMLDocument':
      default:
        domRoot = parentNode.head;
        break;
    }
```

But not entirely sure if this is safe or if it'll break something else.

**Comment by kraMaddi** [comment]
Getting the same issue for safari as well.
hierarchyrequesterror: the operation would yield an incorrect node tree.
The older version works fine

**Comment by KumarSumitD** [comment]
We are also getting the same error. Is reverting to 4.2.13 fixes the issue ?

**Comment by rossettistone** [comment]
@KumarSumitD Reverting to 4.2.13 resolved the issue for us.

**Comment by handofthecode** [comment]
`HierarchyRequestError: The operation would yield an incorrect node tree.`
Safari: 14.0.3
react-tooltip: 4.2.17

**Comment by dworzycp** [comment]
Same issue here in 4.2.17

**Comment by ruMoonGuard** [comment]
Same issue here in 4.2.19

**Comment by rscotten** [comment]
Confirmed that reverting back to 4.2.13 resolves the issue.
