### ISSUE TITLE
react-tooltip and iframes not working

### ISSUE THREAD

**Issue by ccoffey** [wwayne/react-tooltip#71]
With the following iframe setup, react-tooltips do not work. I think it has something to do with events not working? Any advise?

``` html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Test</title>
  <link rel='stylesheet' href='dist/index.css'>
</head>
<body>
  <div id='main'></div>
  <script>
    var iframe = document.createElement('iframe');
    iframe.style.display = 'none';
    document.body.appendChild(iframe);
    var content = "<!doctype html><head></head><body></body></html>";
    iframe.contentWindow.document.open('text/html', 'replace');
    iframe.contentWindow.document.write(content);
    iframe.contentWindow.document.close();

    var script = iframe.contentWindow.document.createElement("script");
    script.type = "text/javascript";
    script.src = "dist/index.js";
    iframe.contentWindow.document.body.appendChild(script);
  </script>
</body>
</html>
```

Full minimal not working example here: https://github.com/ccoffey/react-tooltip/commit/66a1e70266325b5198c5d26025133bc3ad4b6473

**Comment by wwayne** [comment]
Hi @ccoffey,
I don't have any good solution at the moment and I don't have enough time working on this recently, so you'd better look at other similar library if this is urgent for you.

**Comment by Manuel-Manoury** [comment]
Sorry for grave-digging here ^^' I am working on an iframe-contained widget, thus I tend to face this kind of issue quite often with my UI dependencies. A way to make the component work with iframes would be to use `context` in order to define the `document` node to be used (specially for the style which is appended to the `head` node). Component Context is not something we should use a lot, but I think in this particular case, it makes sense. Otherwise, we could specify the `document` to be used as a prop passed to the Component.
